"""Transport layer helpers for Protocol Runtime."""

from .base import TransportMetadata, metadata_from_response, pick_forward_headers
from .http import HttpStreamRequest, open_stream
from .http_runtime import (
    HttpBodyReadResult,
    HttpStreamReadStep,
    HttpStreamStartResult,
    OpenedHttpResponse,
    StreamAsNonStreamResult,
    aggregate_stream_as_non_stream_response,
    close_proxy_client,
    close_response_context,
    open_response_with_proxy_chain,
    prepare_stream_response_start,
    read_next_stream_step,
    read_http_error_response,
    read_non_stream_body,
)
from .policy import (
    pick_non_direct_proxy_name,
    proxy_byte_snapshot,
    proxy_route_kwargs,
    responses_upstream_ws_enabled,
    should_use_responses_upstream_ws,
)
from .websocket import event_type as ws_event_type, frame_size as ws_frame_size
from .ws_runtime import (
    ManagedWsConnection,
    ResponsesWsReadStep,
    ResponsesWsPreVisibleResult,
    WsProxyBytes,
    connect_upstream_ws,
    http_url_to_ws,
    legacy_socks5_connector,
    open_socket_via_ss2022,
    read_next_responses_ws_step,
    read_until_first_responses_ws_visible_event,
    resolve_ws_route_chain,
    socks5h_url,
    ws_route_kwargs,
)

__all__ = [
    "TransportMetadata",
    "metadata_from_response",
    "pick_forward_headers",
    "HttpStreamRequest",
    "open_stream",
    "HttpBodyReadResult",
    "HttpStreamReadStep",
    "HttpStreamStartResult",
    "OpenedHttpResponse",
    "StreamAsNonStreamResult",
    "aggregate_stream_as_non_stream_response",
    "close_proxy_client",
    "close_response_context",
    "open_response_with_proxy_chain",
    "prepare_stream_response_start",
    "read_next_stream_step",
    "read_http_error_response",
    "read_non_stream_body",
    "pick_non_direct_proxy_name",
    "proxy_byte_snapshot",
    "proxy_route_kwargs",
    "responses_upstream_ws_enabled",
    "should_use_responses_upstream_ws",
    "ws_event_type",
    "ws_frame_size",
    "ManagedWsConnection",
    "ResponsesWsReadStep",
    "ResponsesWsPreVisibleResult",
    "WsProxyBytes",
    "connect_upstream_ws",
    "http_url_to_ws",
    "legacy_socks5_connector",
    "open_socket_via_ss2022",
    "read_next_responses_ws_step",
    "read_until_first_responses_ws_visible_event",
    "resolve_ws_route_chain",
    "socks5h_url",
    "ws_route_kwargs",
]
